# numerical sequence

## naive recursion

In [ ]:
#
def fibonacci(n):
    if n == 1:
        return 0
    if n == 2:
        return 1
    return fibonacci(n-1)+fibonacci(n-2)
print(1, fibonacci(0))

#
def fib_to(n):
    fibs = [0, 1]
    for i in range(2, n+1):
        fibs.append(fibs[-1] + fibs[-2])
    return fibs
print(2, fib_to(6-1))

#
FibArray = [0, 1]
def fibonacci(n):
    if n <= len(FibArray):
        return FibArray[n - 1]
    else:
        temp_fib = fibonacci(n - 1) + fibonacci(n - 2)
        FibArray.append(temp_fib)
        return temp_fib
print(3, fibonacci(6))

# nested safes

In [79]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 10, size=(10, 4)), columns=list('ABCD'))
df.values

array([[0, 0, 5, 2],
       [8, 5, 4, 2],
       [9, 0, 8, 6],
       [9, 2, 7, 1],
       [1, 9, 2, 3],
       [8, 1, 1, 6],
       [8, 8, 0, 0],
       [0, 1, 3, 0],
       [2, 4, 5, 3],
       [4, 0, 9, 7]])

In [85]:
df = pd.DataFrame([
    [3, 2, 5, 2],
    [8, 5, 4, 2],
    [9, 0, 8, 6],
    [9, 2, 7, 1],
    [1, 9, 2, 3],
    [8, 1, 1, 6],
    [8, 8, 0, 0],
    [0, 1, 3, 0],
    [2, 4, 5, 3],
    [4, 0, 9, 7]
])
df

0  1  2  3
0  3  2  5  2
1  8  5  4  2
2  9  0  8  6
3  9  2  7  1
4  1  9  2  3
5  8  1  1  6
6  8  8  0  0
7  0  1  3  0
8  2  4  5  3
9  4  0  9  7

In [ ]:
#PERFECT CASE STUDY
def rec(list1, n, iter):
    a = df.iloc[n].to_list()

    if iter == 3:
        return 0

    list1.append(n)
    print(list1)

    for subn in a:
        rec(list1, subn, iter+1)

rec([], 0, 0)

In [95]:
df.values[0]

array([3, 2, 5, 2], dtype=int64)

In [101]:
df.values[0]

array([3, 2, 5, 2], dtype=int64)

In [107]:
df

0  1  2  3
0  3  2  5  2
1  8  5  4  2
2  9  0  8  6
3  9  2  7  1
4  1  9  2  3
5  8  1  1  6
6  8  8  0  0
7  0  1  3  0
8  2  4  5  3
9  4  0  9  7

In [9]:
import pandas as pd
df = pd.DataFrame([
    [3, 2, 5, 2],
    [8, 5, 4, 2],
    [9, 0, 8, 6],
    [9, 2, 7, 1],
    [1, 9, 2, 3],
    [8, 1, 1, 6],
    [8, 8, 0, 0],
    [0, 1, 3, 0],
    [2, 4, 5, 3],
    [4, 0, 9, 7]
])
df

counter = 0
for a in range(3):
    for b in range(3):
        for c in range(3):
            print(counter, '_', 0, a, b, c)
            df.values[]
            counter = counter+1
            if c == 2:
                counter = 0

0 _ 0 0 0 0
1 _ 0 0 0 1
2 _ 0 0 0 2
0 _ 0 0 1 0
1 _ 0 0 1 1
2 _ 0 0 1 2
0 _ 0 0 2 0
1 _ 0 0 2 1
2 _ 0 0 2 2
0 _ 0 1 0 0
1 _ 0 1 0 1
2 _ 0 1 0 2
0 _ 0 1 1 0
1 _ 0 1 1 1
2 _ 0 1 1 2
0 _ 0 1 2 0
1 _ 0 1 2 1
2 _ 0 1 2 2
0 _ 0 2 0 0
1 _ 0 2 0 1
2 _ 0 2 0 2
0 _ 0 2 1 0
1 _ 0 2 1 1
2 _ 0 2 1 2
0 _ 0 2 2 0
1 _ 0 2 2 1
2 _ 0 2 2 2


In [163]:
n_1 = 0
n_2 = df.values[n_1][0]
n_3 = df.values[n_2][0]
n_4 = df.values[n_3][0]

n_5 = 0
n_6 = df.values[n_5][0]
n_7 = df.values[n_6][0]
n_8 = df.values[n_7][1]

n_9 = 0
n_10 = df.values[n_9][0]
n_11 = df.values[n_10][0]
n_12 = df.values[n_11][2]

n_13 = 0
n_14 = df.values[n_13][0]
n_15 = df.values[n_14][0]
n_16 = df.values[n_15][3]

n_17 = 0
n_18 = df.values[n_17][0]
n_19 = df.values[n_18][1]
n_20 = df.values[n_19][0]


last_n = 20
[exec('print("n_{var}", n_{var})'.format(var=x)) for x in range(1, last_n+1)]
None

n_1 0
n_2 3
n_3 9
n_4 4
n_5 0
n_6 3
n_7 9
n_8 0
n_9 0
n_10 3
n_11 9
n_12 9
n_13 0
n_14 3
n_15 9
n_16 7
n_17 0
n_18 3
n_19 2
n_20 9


In [14]:
#PERFECT CASE STUDY
def rec(list1, n, iter):
    if iter == 3:
        return 0
    a = point_tree.query_ball_point(df.iloc[n], 2.5)
    a.remove(n)
    print(n, a)
    for subn in a: 
        rec(list1, subn, iter+1)

rec([], 7, 0)

[6, 5, 2, 3]

In [10]:
arr = df.to_numpy()

staging = [[0]] #initial value
result = []
while len(staging) > 0:
    s = staging.pop(0)
    if len(s) == 4:
        #iteration has ended
        result.append(s)
    else:
        last = s[-1]
        for i in range(4): #valori laterali
            staging.append(s + [arr[last, i]])
result

[[0, 3, 9, 4],
 [0, 3, 9, 0],
 [0, 3, 9, 9],
 [0, 3, 9, 7],
 [0, 3, 2, 9],
 [0, 3, 2, 0],
 [0, 3, 2, 8],
 [0, 3, 2, 6],
 [0, 3, 7, 0],
 [0, 3, 7, 1],
 [0, 3, 7, 3],
 [0, 3, 7, 0],
 [0, 3, 1, 8],
 [0, 3, 1, 5],
 [0, 3, 1, 4],
 [0, 3, 1, 2],
 [0, 2, 9, 4],
 [0, 2, 9, 0],
 [0, 2, 9, 9],
 [0, 2, 9, 7],
 [0, 2, 0, 3],
 [0, 2, 0, 2],
 [0, 2, 0, 5],
 [0, 2, 0, 2],
 [0, 2, 8, 2],
 [0, 2, 8, 4],
 [0, 2, 8, 5],
 [0, 2, 8, 3],
 [0, 2, 6, 8],
 [0, 2, 6, 8],
 [0, 2, 6, 0],
 [0, 2, 6, 0],
 [0, 5, 8, 2],
 [0, 5, 8, 4],
 [0, 5, 8, 5],
 [0, 5, 8, 3],
 [0, 5, 1, 8],
 [0, 5, 1, 5],
 [0, 5, 1, 4],
 [0, 5, 1, 2],
 [0, 5, 1, 8],
 [0, 5, 1, 5],
 [0, 5, 1, 4],
 [0, 5, 1, 2],
 [0, 5, 6, 8],
 [0, 5, 6, 8],
 [0, 5, 6, 0],
 [0, 5, 6, 0],
 [0, 2, 9, 4],
 [0, 2, 9, 0],
 [0, 2, 9, 9],
 [0, 2, 9, 7],
 [0, 2, 0, 3],
 [0, 2, 0, 2],
 [0, 2, 0, 5],
 [0, 2, 0, 2],
 [0, 2, 8, 2],
 [0, 2, 8, 4],
 [0, 2, 8, 5],
 [0, 2, 8, 3],
 [0, 2, 6, 8],
 [0, 2, 6, 8],
 [0, 2, 6, 0],
 [0, 2, 6, 0]]

In [8]:
todo = set()

todo.add(0)
todo.add(1)
todo.add(5)
todo.add('a')

todo.add(4)

todo

{0, 1, 4, 5, 'a'}

In [ ]:
import pandas as pd
df = pd.DataFrame([
    [3, 2, 5, 2],
    [8, 5, 4, 2],
    [9, 0, 8, 6],
    [9, 2, 7, 1],
    [1, 9, 2, 3],
    [8, 1, 1, 6],
    [8, 8, 0, 0],
    [0, 1, 3, 0],
    [2, 4, 5, 3],
    [4, 0, 9, 7]
])
df

done = list()
todo = [0, 3]

iter = 0
while iter < 3:
    print('new', iter, done, todo)
    tomove = len(todo)
    todo_ = todo.copy() #we copy 
    for el in todo_:
        print('inside', el, list(df.iloc[el]))
        [todo.append(x) for x in list(df.iloc[el])]
        
    done = done+todo[0:tomove]
    todo = todo[tomove:]
    
    iter += 1

In [ ]:
done = list()
todo = [0, 3]

iter = 0
while iter < 3:
    print('new', iter, done, todo)
    tomove = len(todo)
    todo_ = todo.copy() #we copy 
    for el in todo_:
        print('inside', el, list(df.iloc[el]))
        [todo.append(x) for x in list(df.iloc[el])]
        
    done = done+todo[0:tomove]
    todo = todo[tomove:]
    
    iter += 1