In [ ]:
import numpy as np
import random
import pandas as pd

def simulation(n_players, max_wins, n_lives):
  class player:
    lives = n_lives
    consecutive_wins = 0

    def __init__(self):
      pass

  def pick_alive():
    return pool_alive.pop(random.randint(0, len(pool_alive)-1))

  def fight(max_wins):
    try:
      a = pick_alive()
      b = pick_alive()

      #result
      result = random.randint(0, 1)
      
      if result == 0:
        a.lives -= 1
        b.consecutive_wins += 1
      else:
        b.lives -= 1
        a.consecutive_wins += 1
      
      #print(result, 'a:', a.lives, 'b:', b.lives)
      #die or live
      if a.consecutive_wins == max_wins:
        pool_done.append(a)
      else:
        if a.lives == 0:
          pool_done.append(a)
        else:
          pool_alive.append(a)

      if b.consecutive_wins == max_wins:
        pool_done.append(b)
      else:
        if b.lives == 0:
          pool_done.append(b)
        else:
          pool_alive.append(b)

      #print('tried', pool_alive, a.lives, b.lives, pool_done)
    except:
      #print(pool_alive, 'k')
      #last player remaining
      pool_done.append(a)
      return 0

  #print(len(pool_alive))

  pool_alive = [player() for x in range(n_players)]
  pool_done = list()

  #fight until there is no one left
  #last player gets moved into the other bracket
  while len(pool_alive) > 0:
    if fight(max_wins) == 0:
      break

  players_done = list()
  for d in pool_done:
    players_done.append([d.lives, d.consecutive_wins])

  players_alive = list()
  for k in pool_alive:
    players_alive.append([k.lives, k.consecutive_wins])

  total = pd.DataFrame(players_done+players_alive)
  total

  return total, total[1][total[1]==12].count()/n_players

_, winners = simulation(1000000, 12, 3)
winners

0.006397

In [ ]:
import numpy as np

a = [[['a', 'l']], [['a', 'h']]]

def prepare_dict(list1):
  list1 = np.array(list1).flatten()

  #create set
  set1 = set()
  [set1.add(el) for el in list1]

  #create dict
  label_2_int = {list(set1)[i]:i for i in range(len(list(set1)))}
  return label_2_int

def index_based_encoder(list1, label_2_int):
  list1 = np.array(list1).flatten()
  #index-based encoding
  y_index = [label_2_int[el] for el in list1]
  return y_index

def one_hot_encoder(list1, label_2_int):
  list1 = np.array(list1).flatten()

  #one_hot encoding
  def fill_array(array, index):
    array[index] = 1
    return array

  #index-based encoding
  y_one_hot = [fill_array(np.zeros(len(label_2_int)), el) for el in list1]
  return y_one_hot

label_2_int = prepare_dict(a)
y_index = index_based_encoder(a, label_2_int)
y_one_hot = one_hot_encoder(y_index, label_2_int)

print('y:', '\n', np.array(a), '\n_______________')
print('y_index:', '\n', np.array(y_index), '\n_______________')
print('y_one_hot:', '\n', np.array(y_one_hot))

y: 
 [[['a' 'l']]

 [['a' 'h']]] 
_______________
y_index: 
 [0 2 0 1] 
_______________
y_one_hot: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
a

[[['a', 'l']], [['a', 'h']]]

In [ ]:
a
np.unique(a)



array(['a', 'h', 'l'], dtype='<U1')

In [ ]:
l = {1: 5, 4:4}
len(l)

2

In [ ]:


import numpy as np

y = [['cake'], ['tiramisu'], ['cake'], ['sacher']]

#   create index-based encoding dict
#fill set
set1 = set()
[[set1.add(el) for el in a] for a in y]

#create dict
label_2_int = {list(set1)[i]:i for i in range(len(list(set1)))}

#index-based encoding
y_index = [[label_2_int[el] for el in a] for a in y]

#one_hot encoding
def fill_array(array, index):
  array[index] = 1
  return array

y_one_hot = [[fill_array(np.zeros(len(set1)), el) for el in a] for a in y_index]

print('y:', '\n', np.array(y), '\n_______________')
print('y_index:', '\n', np.array(y_index), '\n_______________')
print('y_one_hot:', '\n', np.array(y_one_hot))
\
y: 
 [['cake']
 ['tiramisu']
 ['cake']
 ['sacher']] 
_______________
y_index: 
 [[2]
 [1]
 [2]
 [0]] 
_______________
y_one_hot: 
 [[[0. 0. 1.]]
 [[0. 1. 0.]]
 [[0. 0. 1.]]
 [[1. 0. 0.]]]


array(['a', 'l', 'b', 'h'], dtype='<U1')